name: pemrograman_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: 0.20.2
  uuid: ^4.5.1

  fl_chart: ^0.66.0      
  csv: ^6.0.0            
  pdf: ^3.10.7           
  path_provider: ^2.1.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
